const initConfig = require('./start/init-config')
const injection = require('./start/injection')
const listen = require('./start/listen')
const handlePlugins = require('./start/handle-plugins')
const handleMisc = require('./start/handle-misc')
const handleNduts = require('./start/handle-nduts')
const postHandleNduts = require('./start/post-handle-nduts')
const handleRoutes = require('./start/handle-routes')
const configurePlugins = require('./start/configure-plugins')
const helper = require('./start/helper')
require('log-timestamp')

module.exports = async function (options = {}) {
  const { fastify, actions, ndutsActions } = await initConfig()
  fastify.decorate('ndut', { helper: helper(fastify) })
  await injection(fastify, 'config', options)
  const oldPlugins = await configurePlugins(fastify)
  await injection(fastify, 'plugins', options, ndutsActions)
  const ndutsPlugins = await handleNduts(fastify, actions)
  await injection(fastify, 'nduts', options, ndutsActions)
  await handlePlugins(fastify, oldPlugins)
  await postHandleNduts(fastify, ndutsPlugins)
  await handleRoutes(fastify)
  await injection(fastify, 'routes', options)
  await handleMisc(fastify)
  await injection(fastify, 'misc', options)
  await listen(fastify)
}
