const initConfig = require('./start/init-config')
const injection = require('./start/injection')
const listen = require('./start/listen')
const handlePlugins = require('./start/handle-plugins')
const handleMisc = require('./start/handle-misc')
const handleNduts = require('./start/handle-nduts')
const postHandleNduts = require('./start/post-handle-nduts')
const handleRoutes = require('./start/handle-routes')
const configurePlugins = require('./start/configure-plugins')
const buildHelper = require('./start/helper')
require('log-timestamp')

module.exports = async function (options = {}) {
  const { fastify, actions, ndutsActions } = await initConfig()
  const helper = await buildHelper.call(fastify)
  fastify.decorate('ndut', { helper })
  await injection.call(fastify, 'config', options)
  const oldPlugins = await configurePlugins.call(fastify)
  await injection.call(fastify, 'plugins', options, ndutsActions)
  const nduts = await handleNduts.call(fastify, actions)
  await injection.call(fastify, 'nduts', options, ndutsActions)
  await handlePlugins.call(fastify, oldPlugins)
  await postHandleNduts.call(fastify, nduts)
  await handleRoutes.call(fastify)
  await injection.call(fastify, 'routes', options)
  await handleMisc.call(fastify)
  await injection.call(fastify, 'misc', options)
  await listen.call(fastify)
}
