const initConfig = require('./start/init-config')
const injection = require('./start/injection')
const listen = require('./start/listen')
const handlePlugins = require('./start/handle-plugins')
const handleDefaults = require('./start/handle-defaults')
const handleNduts = require('./start/handle-nduts')
const postHandleNduts = require('./start/post-handle-nduts')
const handleRoutes = require('./start/handle-routes')
const configurePlugins = require('./start/configure-plugins')
const initHelper = require('./helper/init')
require('log-timestamp')

module.exports = async function (options = {}) {
  const { scope, actions, ndutsActions } = await initConfig()
  const helper = await initHelper.call(scope)
  scope.decorate('ndut', { helper })
  await injection.call(scope, 'config', options)
  await handleDefaults.call(scope)
  const oldPlugins = await configurePlugins.call(scope)
  await injection.call(scope, 'plugins', options, ndutsActions)
  const nduts = await handleNduts.call(scope, actions, ndutsActions)
  await injection.call(scope, 'nduts', options, ndutsActions)
  await handlePlugins.call(scope, oldPlugins)
  await postHandleNduts.call(scope, nduts)
  await handleRoutes.call(scope)
  await injection.call(scope, 'routes', options)
  // await injection.call(scope, 'misc', options)
  await listen.call(scope)
  return scope
}
